// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for drizzle.__drizzle_migrations */
export type DrizzleMigrationsId = number & { __brand: 'drizzle.__drizzle_migrations' };

/** Represents the table drizzle.__drizzle_migrations */
export default interface DrizzleMigrations {
  id: DrizzleMigrationsId;

  hash: string;

  created_at: string | null;
}

/** Represents the initializer for the table drizzle.__drizzle_migrations */
export interface DrizzleMigrationsInitializer {
  /** Default value: nextval('drizzle.__drizzle_migrations_id_seq'::regclass) */
  id?: DrizzleMigrationsId;

  hash: string;

  created_at?: string | null;
}

/** Represents the mutator for the table drizzle.__drizzle_migrations */
export interface DrizzleMigrationsMutator {
  id?: DrizzleMigrationsId;

  hash?: string;

  created_at?: string | null;
}
