// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.todos */
export type TodosId = string & { __brand: 'public.todos' };

/** Represents the table public.todos */
export default interface Todos {
  id: TodosId;

  name: string;

  isComplete: boolean;

  createdAt: Date;

  updatedAt: Date;
}

/** Represents the initializer for the table public.todos */
export interface TodosInitializer {
  /** Default value: gen_random_uuid() */
  id?: TodosId;

  name: string;

  isComplete: boolean;

  /** Default value: now() */
  createdAt?: Date;

  /** Default value: now() */
  updatedAt?: Date;
}

/** Represents the mutator for the table public.todos */
export interface TodosMutator {
  id?: TodosId;

  name?: string;

  isComplete?: boolean;

  createdAt?: Date;

  updatedAt?: Date;
}
